
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='pyppeteer',
    version='0.2.5',
    description='Headless chrome/chromium automation library (unofficial port of puppeteer)',
    python_requires='==3.*,>=3.6.1',
    project_urls={"homepage": "https://github.com/pyppeteer/pyppeteer", "repository": "https://github.com/pyppeteer/pyppeteer"},
    author='granitosaurus',
    author_email='bernardas.alisauskas@pm.me',
    maintainer='Hiroyuki Takagi',
    maintainer_email='miyako.dev@gmail.com',
    license='MIT',
    keywords='pyppeteer puppeteer chrome chromium',
    classifiers=['Development Status :: 3 - Alpha', 'Intended Audience :: Developers', 'License :: OSI Approved :: MIT License', 'Natural Language :: English', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'Programming Language :: Python :: 3.9'],
    entry_points={"console_scripts": ["pyppeteer-install = pyppeteer.command:install"]},
    packages=['pyppeteer'],
    package_dir={"": "."},
    package_data={},
    install_requires=['appdirs==1.*,>=1.4.3', 'importlib-metadata==2.*,>=2.1.1; python_version < "3.8"', 'pyee==8.*,>=8.1.0', 'tqdm==4.*,>=4.42.1', 'urllib3==1.*,>=1.25.8', 'websockets==8.*,>=8.1.0'],
    extras_require={"dev": ["flake8==3.*,>=3.7.9", "livereload==2.*,>=2.6.1", "m2r==0.*,>=0.2.1", "mypy==0.*,>=0.770.0", "pre-commit==2.*,>=2.2.0", "pydocstyle==5.*,>=5.0.2", "pylint==2.*,>=2.4.4", "pytest==5.*,>=5.3.5", "pytest-cov==2.*,>=2.8.1", "pytest-xdist==1.*,>=1.31.0", "readme-renderer==24.*,>=24.0.0", "sphinx==2.*,>=2.4.0", "sphinxcontrib-asyncio==0.*,>=0.2.0", "syncer==1.*,>=1.3.0", "tox==3.*,>=3.20.1"]},
)
